# BASE
FROM node:24-alpine AS base

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl \
      make \
      python3 \
      libc6-compat

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

RUN npm install -g turbo
RUN npm install -g pnpm

# PRUNER
FROM base AS pruner

WORKDIR /var/web/

COPY . .
RUN turbo prune --scope=@sep/events-admin-rest-api --docker

# INSTALLER
# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer

WORKDIR /var/web

COPY --from=pruner /var/web/out/json/ .
COPY --from=pruner /var/web/out/pnpm-lock.yaml .

RUN pnpm install --frozen-lockfile

# BUILDER
FROM base AS builder

WORKDIR /var/web

# Build the project
COPY --from=installer /var/web .
COPY --from=pruner /var/web/out/full/ .

RUN turbo run build --filter="@sep/events-admin-rest-api"

# RUNNER
FROM base AS runner

WORKDIR /var/web

# Don't run production as root
RUN addgroup --system --gid 1001 nodes && adduser --system --uid 1001 nodejs
USER nodejs

COPY --from=builder --chown=nodejs:nodes /var/web .