# BASE
FROM node:22-alpine AS base

RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl \
      make \
      python3 \
      libc6-compat

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

RUN npm install -g turbo
RUN npm install -g pnpm

# BUILDER
FROM base AS builder

WORKDIR /var/web/

COPY . .
RUN turbo prune --scope=@sep/events-service --docker

# INSTALLER
# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer

WORKDIR /var/web

# First install the dependencies (as they change less often)
COPY .gitignore .gitignore
COPY --from=builder /var/web/out/json/ .
COPY --from=builder /var/web/out/pnpm-lock.yaml .
COPY --from=builder /var/web/services/events-service/prisma ./prisma
COPY --from=builder /var/web/services/events-service/prisma.config.ts ./prisma.config.ts

RUN pnpm install --frozen-lockfile

# Build the project
COPY --from=builder /var/web/out/full/ .
COPY turbo.json turbo.json

RUN turbo run build --filter="@sep/events-service"

# RUNNER
FROM base AS runner

WORKDIR /var/web

# Don't run production as root
RUN addgroup --system --gid 1001 nodes && adduser --system --uid 1001 nodejs
USER nodejs

COPY --from=installer --chown=nodejs:nodes /var/web .